### PR TITLE
Add basic documentation for API

### LINKED ISSUE #8: Add API documentation

### PR DESCRIPTION
**Pull request by sobolevnrm**
Fixes #8.

### CODE REVIEW

**Comment by sobolevnrm** [comment]
@intendo - thanks for merging but I was hoping @speleo3 could finish his review first.  It's probably not worth backing the changes out at this point but I'd still appreciate @speleo3 comments -- we can generate a new PR to address them, if needed.

**Comment by intendo** [comment]
I apologize. I looked at this on my phone app and did not see @speleo3 in the reviewers list. In the browser on my computer I see him. We can restore the branch and back out the merge if needed.

**Comment by speleo3** [comment]
No need to revert the merge, I think any comments can be addressed with follow-up PRs.

Some thoughts:
- Should add basic usage examples
- Should add method documentation for `DataContainer` and `DataCategory`

Things I noticed, but are not directly related to this PR:
- `pdbx.containers.CifName` is never used and should be removed
- The parser's support for **save frames** (`DefinitionContainer`) seems to be incomplete/incorrect. They get added to the top-level container list instead of their parent `DataContainer`.

Other thoughts on the API (minor wish-list):
- Looking again at `json` and `pickle`: They put everything API relevant in the top-level module namespace. E.g. [json.JSONDecoder](https://docs.python.org/3/library/json.html#json.JSONDecoder) instead of [json.decoder.JSONDecoder](https://github.com/python/cpython/blob/c77f71f9819022fa3adeb2f710e564a392ff24c6/Lib/json/decoder.py#L254) (actual implementation). _"Flat is better than nested" ([The Zen of Python](https://www.python.org/dev/peps/pep-0020/))_ so to speak.

**Comment by intendo** [comment]
I definitely like flatter namespaces.

**Comment by sobolevnrm** [comment]
@intendo if you have time can you break @speleo3's feedback into multiple (3-4) new issues so we can track?

**Comment by intendo** [comment]
@sobolevnrm Done.

**Pull request merged**
