### PR TITLE
Create CODE_OF_CONDUCT.md

### PR DESCRIPTION
**Pull request by sobolevnrm**

### CODE REVIEW

**Review by intendo — APPROVED** [review]

**Comment by orbeckst** [comment]
Adapting a code of conduct is good. Two points to consider:
- Link it from the documentation and the top level README.
- Having an individual's email address as the CoC address could be problematic if there's a real or perceived conflict of interest. At MDAnalysis we have a few people that are tasked with CoC and a generic email that routes to all of them (a Google group that allows posting by all but only reading by the CoC committee).

**Comment by speleo3** [comment]
> I've created [mmcif_pdbx@googlegroups.com](mailto:mmcif_pdbx@googlegroups.com) per the suggestion from @orbeckst. Can you email that address with the email you'd like to have included?

Not sure if that worked. I got this reply:

> We're writing to let you know that the group you tried to contact (mmcif_pdbx) may not exist, or you may not have permission to post messages to the group. ...

**Comment by orbeckst** [comment]
I got the same reply on emailing as https://github.com/Electrostatics/mmcif_pdbx/pull/55#issuecomment-810406322.

**Comment by sobolevnrm** [comment]
I might have to add you first.  Can you please just email me your preferred address at nathanandrewbaker@gmail.com instead?

**Pull request merged**
